### ISSUE TITLE
Support armv7l

### ISSUE THREAD

**Issue by danpoltawski** [moodlehq/moodle-php-apache#158] opened 2022-08-05 14:44 UTC
It'd be nice to support armv7l so can run on rpi4 (at least for simple dbs)

**Comment by andrewnicols** [comment] 2022-08-05 14:58
Hi Dan,

We currently cross-compile during the [GHA build](https://github.com/moodlehq/moodle-php-apache/blob/master/.github/workflows/test_buildx_and_publish.yml#L88).

Do you know whether armv7l support is included in the arm arch? The php image is available for both arm64, and arm (https://hub.docker.com/_/php), but the Docker docs are impressively vague on the compatibility: https://docs.docker.com/desktop/multi-arch/ and the DockerHub official image include arm32v6, arm32v7, and arm64v8 but not arm. I'm assuming that the arm arch covers the 32-bit variants but I haven't been able to find anything to confirm and I don't have a spare Rpi4 hanging around to just check.

If you're able to submit a PR then I can review.

**Comment by stronk7** [comment] 2022-08-06 22:54
I'm ok building the arm32v7 architecture images, np with that.

Only question that I've about that is if we really need them, specifically for the Raspi... they have arm64 cpus since ages ago (2017 or earlier) and there are 64 OSs for many them... so current arm64[v8] builds should work without problem, isn't it?

https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by scara** [comment] 2023-01-29 21:00
Hello Everyone,
> so current arm64[v8] builds should work without problem, isn't it?

Confirmed via https://github.com/moodlehq/moodle-docker/issues/248#issuecomment-1407758706.

HTH,
Matteo

**Comment by andrewnicols** [comment] 2023-03-19 14:42
I'm going to close this issue:
* confirmed as working
* Moodle 4.2 onwards no longer supports 32-bit anyway.

**Closed by andrewnicols** 2023-03-19 14:42 UTC
